config/routes.rb
Rails.application.routes.draw do
  root "home#welcome"
  get 'dashboard/index', to: 'dashboard#index', as: :dashboard

  # user sign up
  get "sign_up", to: "users#new", as: :sign_up
  post "sign_up", to: "users#create"
  get 'confirmations/confirm_email/:confirmation_token', to: 'confirmations#confirm_email', as: :email_confirmation

  # user sign in
  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  # user assets crud
  resources :user_assets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  email            :string           not null
#  password_digest  :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  confirmed_at      :datetime
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  has_many :user_assets, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates :password, length: { minimum: 6 }

  def confirm!
    update_columns(confirmed_at: Time.current)
  end

  def confirmed?
    confirmed_at.present?
  end

  def unconfirmed?
    !confirmed?
  end

  def generate_confirmation_token
    signed_id expires_in: 15.minutes
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end
end

app/models/user_asset.rb
# == Schema Information
#
# Table name: user_assets
#
#  id                      :bigint           not null, primary key
#  item_name               :string           not null
#  purchase_price_cents    :integer          not null
#  purchase_price_currency :string           default("AUD"), not null
#  purchase_date           :date             not null
#  user_id                 :integer          not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_user_assets_on_user_id  (user_id)
#

class UserAsset < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticated
end

app/controllers/concerns/authenticated.rb
module Authenticated
  extend ActiveSupport::Concern

  included do
    before_action :current_user
    helper_method :current_user
    helper_method :user_signed_in?
  end

  def current_user
    if session[:current_user_id]
      current_user ||= User.find_by(id: session[:current_user_id])
    end
  end

  def user_signed_in?
    current_user.present?
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def confirm_email
    @user = User.find_signed(params[:confirmation_token])

    if @user.present?
      @user.confirm!
      redirect_to root_path, notice: "Your account has been confirmed."
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.authenticate(params[:user][:password])
        reset_session
        session[:current_user_id] = @user.id
        redirect_to dashboard_index_path, notice: "Signed in."
      else
        flash.now[:alert] = "Incorrect email or password."
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Incorrect email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/user_assets_controller.rb
class UserAssetsController < ApplicationController
  before_action :set_user_asset, only: [:show, :edit, :update, :destroy]

  # GET /user_assets
  def index
    @user_assets = current_user.user_assets
  end

  # GET /user_assets/1
  def show
  end

  # GET /user_assets/new
  def new
    @user_asset = UserAsset.new
  end

  # POST /user_assets
  def create
    @user_asset = current_user.user_assets.build(user_asset_params)

    if @user_asset.save
      redirect_to @user_asset, notice: 'User asset was successfully created.'
    else
      render :new
    end
  end

  # GET /user_assets/1/edit
  def edit
  end

  # PUT /user_assets/1
  def update
    if @user_asset.update(user_asset_params)
      redirect_to @user_asset, notice: "User asset was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /user_assets/1
  def destroy
    @user_asset.destroy
    redirect_to user_assets_url, notice: "User asset was successfully destroyed."
  end

  private

    def set_user_asset
      @user_asset = current_user.user_assets.find(params[:id])
    end

    def user_asset_params
      params.require(:user_asset).permit(:item_name, :purchase_price_cents, :purchase_price_currency, :purchase_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      debugger
      @user.send_confirmation_email!
      redirect_to root_path, notice: 'A confirmation email has been sent to your registered email.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_assets_helper.rb
module UserAssetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<p>Welcome, <%= current_user.email %></p>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FireRunway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to 'Dashboard', dashboard_path %></li>
      <li><%= link_to 'User Assets', user_assets_path %></li>
    <li><%= link_to 'Log out', logout_path, data: { turbo_method: :delete } %></li>
    <% else %>
        <li><%= link_to 'Sign up', sign_up_path %></li>
        <li><%= link_to 'Login', login_path %></li>
    <% end %>
  </ul>

app/views/user_assets/create.html.erb
<h1>UserAssets#create</h1>
<p>Find me in app/views/user_assets/create.html.erb</p>

app/views/user_assets/destroy.html.erb
<h1>UserAssets#destroy</h1>
<p>Find me in app/views/user_assets/destroy.html.erb</p>

app/views/user_assets/edit.html.erb
<h1>UserAssets#edit</h1>

<%= form_with(model: @user_asset, local: true) do |form| %>
  <% if @user_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_asset.errors.count, "error") %> prohibited this user_asset from being saved:</h2>

      <ul>
        <% @user_asset.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :purchase_price_cents %>
    <%= form.number_field :purchase_price_cents %>
  </div>

  <div class="field">
    <%= form.label :purchase_price_currency %>
    <%= form.text_field :purchase_price_currency %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.date_select :purchase_date %>
  </div>

  <div class="actions">
    <%= form.submit "Save changes" %>
  </div>
<% end %>

<%= link_to 'Back', @user_asset %>

app/views/user_assets/index.html.erb
<h1>UserAssets#index</h1>
<p>Find me in app/views/user_assets/index.html.erb</p>

<%= link_to 'New User Asset', new_user_asset_path %>

<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Purchase Price (Cents)</th>
      <th>Purchase Price Currency</th>
      <th>Purchase Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_assets.each do |user_asset| %>
      <tr>
        <td><%= user_asset.item_name %></td>
        <td><%= user_asset.purchase_price_cents %></td>
        <td><%= user_asset.purchase_price_currency %></td>
        <td><%= user_asset.purchase_date %></td>
        <td><%= link_to 'Show', user_asset %></td>
        <td><%= link_to 'Edit', edit_user_asset_path(user_asset) %></td>
        <td><%= link_to 'Destroy', user_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_assets/new.html.erb
<h1>UserAssets#new</h1>
<p>Find me in app/views/user_assets/new.html.erb</p>

<%= form_for @user_asset, html: { multipart: true } do |f| %>
  <%= f.label :item_name %>
  <%= f.text_field :item_name %>
  <br>

  <%= f.label :purchase_price_cents %>
  <%= f.number_field :purchase_price_cents %>
  <br>

  <%= f.label :purchase_price_currency %>
  <%= f.text_field :purchase_price_currency, value: "AUD" %>
  <br>

  <%= f.label :purchase_date %>
  <%= f.date_select :purchase_date %>
  <br>

  <%= f.submit %>
<% end %>

app/views/user_assets/show.html.erb
<h1>UserAssets#show</h1>

<p>
  <strong>Item Name:</strong>
  <%= @user_asset.item_name %>
</p>

<p>
  <strong>Purchase Price:</strong>
  <%= number_to_currency(@user_asset.purchase_price_cents / 100.0, unit: @user_asset.purchase_price_currency) %>
</p>

<p>
  <strong>Purchase Date:</strong>
  <%= @user_asset.purchase_date %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @user_asset.created_at %>
</p>

<p>
  <strong>Updated At:</strong>
  <%= @user_asset.updated_at %>
</p>

<%= link_to 'Edit', edit_user_asset_path(@user_asset) %> |
<%= link_to 'Back', user_assets_path %>

app/views/user_assets/update.html.erb
<h1>UserAssets#update</h1>
<p>Find me in app/views/user_assets/update.html.erb</p>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_with model: @user, url: sign_up_path do |form| %>
  <label for="email">
    Email
    <%= form.email_field :email, required: true %>
  </label>
  <label for="password">
    Password
    <%= form.password_field :password, required: true %>
  </label>
  <label for="password_confirmation">
    Password Confirmation
    <%= form.password_field :password_confirmation, required: true %>
  </label>
  <%= form.submit "Sign Up" %>
<% end %>